services:
  - type: web
    name: lyrical-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lyrical.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
