# Generated by Django 6.0.7 on 2026-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunodhun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
