# Generated by Django 6.0.7 on 2026-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunodhun', '0002_song_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('romantic', 'Romantic')], editable=False, max_length=20, null=True),
        ),
    ]
