# Generated by Django 6.0.7 on 2026-07-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunodhun', '0004_likedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('bollywood', 'Bollywood'), ('punjabi', 'Punjabi'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
