# Generated by Django 6.0.7 on 2026-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunodhun', '0006_listeninghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, help_text='LRC format: [00:12.00]Line text', null=True),
        ),
    ]
